---
title: "Case Study 11"
author: Zaque Evans
date: Week 11
output: html
---

```{r echo=FLASE, message=FALSE}
install.packages("ggmap")

install.packages("mapview")
install.packages("tidycensus")
install.packages("foreach")
install.packages("doParallel")
install.packages("lwgeom")
library(lwgeom)
library(tidyverse)
library(spData)
library(sf)
library(ggmap)
library(dplyr)
```


## New Packages to Load
### Actual Census API key not included
```{r }
library(mapview)
library(foreach)
library(doParallel)
registerDoParallel()
getDoParWorkers() # check registered cores
library(tidycensus)
census_api_key(, install = TRUE)

library(tidycensus)
racevars <- c(White = "P005003", 
              Black = "P005004", 
              Asian = "P005006", 
              Hispanic = "P004003")
```
## Creating Useable Census Var objects
```{r echo=FALSE, message=FALSE, warning=FALSE}
options(tigris_use_cache = TRUE)
erie <- get_decennial(geography = "block", variables = racevars, 
                  state = "NY", county = "Erie County", geometry = TRUE,
                  summary_var = "P001001", cache_table=T)

erie
head(erie)

boundary <- c(xmin=-78.9,xmax=-78.85,ymin=42.888,ymax=42.92)

erie_cropped <- st_crop(erie, boundary) 

erie_cropped

erie_raceVar <- as.factor(erie_cropped$variable)

erie_raceVar
str(erie_raceVar)

?levels

erie_RaceDot <- foreach(i = 1:4, .combine = "rbind", .packages = c("sf". "tidyverse")) %dopar% 
  {race <- levels(erie_raceVar)[i]
  erie_cropped %>%
    filter(variable == race) %>%
    st_sample(size = .$value) %>%
    st_as_sf() %>%
    mutate(variable = race)}
    
erie_RaceDot
```
## City of Buffalo Race Dotplot
``` {r echo=FALSE}
erie_dotPlot <- mapview(erie_RaceDot, zcol = "variable", cex = 1)

erie_dotPlot
```

``` {r eval=FALSE echo=FALSE}
rlang::last_error()
```
